server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: burty-files
    static_configs:
      - targets: [localhost]
        labels:
          job: burty
          app: BURTY
          __path__: /var/log/burty/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>[^\]]+)\] (?P<level>\S+) \[(?P<requestId>[^\]]*)\] (?P<logger>\S+) - (?P<message>.*)$'
      - labels:
          level:
          requestId:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
